# Site
repository: chuyuna/chuyuna.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 추유나
title: Server Backend Developer
email: gooddays1202@naver.com
website: https://devuna.tistory.com/

# Dark Mode (true/false/never)
darkmode: false

  # Social links
  # twitter_username: facespics
  # github_username: chuyuna
  # stackoverflow_username: "00000001"
  # dribbble_username: jekyll
  # facebook_username: jekyll
  # flickr_username: jekyll
  # instagram_username: jameswgrant
  # linkedin_username: jameswgrant
  # xing_username: jekyll
  # pinterest_username: jekyll
  # youtube_username: globalmtb
  # googleplus_username: +jekyll
  # orcid_username: 0000-0000-0000-0000

  # Additional icon links
  # additional_links:
  # - title: itsgoingto.be
# icon: fas fa-globe
# url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me https://yunachu.github.io/
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  "함께 일하고 싶은 사람이 되자. 혼자서 할 수 있는 프로젝트는 없다"<br>
  안녕하세요. 5년차 서버 백엔드 개발자 추유나입니다. <br> **MAU 400만 이커머스** 주문/결제/클레임 서비스, **스마트러닝 교육플랫폼 개발기업** 개발자로 근무했습니다.
  <br>MSA 기반의 <mark>대용량 트래픽 처리 분산 아키텍쳐</mark> 경험과 <mark>레거시 시스템 리팩토링 및 운영</mark> 경험이 있으며, <br> 비즈니스 로직을 명확하게 이해하고 원활한 커뮤니케이션으로 협업하는 능력을 가지고 있습니다.


content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: 큐텐테크놀로지
        sub_title: OPC Dev. Team Engineer
        caption: 2023.06 - 재직중
        quote: >
          MAU 437만, 일 주문 35만건 커머스 티몬 주문결제클레임 서비스 개발 및 운영
        description: |
          * 신규 PG사(헥토파이낸셜 내통장결제) 연동 
          * 티몬-큐텐 간 주문/클레임 연동 개발 
          * 신규 쿠폰/할인 파트너 분담금 API / DB 설계 / 어드민 개발 
          * 티몬 주문, 결제, 클레임 업무 운영
      - layout: left
        title: 위메프
        sub_title: 주문결제개발팀 매니저
        caption: 2022.10 - 2023.06
        quote: >
          MAU 432만, 일 주문 30만건 커머스 위메프 주문결제 서비스 개발 및 운영
        description: |
          * 신규 PG사(네이버페이) 연동
          * 위메프 제휴카드 포인트 적립 Spring Batch 리팩토링
          * 위메프 주문, 결제 업무 운영
      - layout: left
        title: 러너스하이
        sub_title: 백엔드개발팀 대리
        caption: 2020.03 - 2022.10
        quote: >
          스마트러닝, 소셜 학습플랫폼 등 교육플랫폼 기반 개발
        description: |
          * 대용량 학습 컨텐츠 일괄 업로드 처리 개발
          * elacticsearch 연동 데이터 검색 개발
  - title: 역량
    layout: list
    content:
      - layout: top-middle
        title: 시스템 개발 및 개선
        quote: >
        description: |
          * 티몬 신규 PG사(헥토파이낸셜 내통장결제) 연동 (리드)
            - 전략 패턴을 사용한 인증결제 서비스 개발
            - 주문/인증/인증완료/승인/승인취소 도메인 로직 분석 및 개발
            - 어드민 내 신규 결제수단 관리 추가
            - 연동사 에러, 내부 시스템 에러 등의 다양한 예외 처리를 위한 ResponseErrorHandler 추가로 응답 일관성 개선
          * 티몬-큐텐 간 주문/클레임 연동 개발 (리드)
            - 티몬 내 판매되는 큐텐 사이트 직구 상품 주문시 주문 정보 API 연동
            - 취소/환불 처리 후 클레임 정보 API 연동
            - 두 사이트 간 주문 일관성 유지를 위해 통신 오류, 주문상태 불일치 등 발생시 트랜잭션 처리, 
              연동건 취소 요청 시 큐텐 내 배송구분값 확인하여 취소 가능 여부 조회 처리
          * 신규 쿠폰/할인 주문 프로세스 API / DB 설계 / 어드민 개발 (리드)
            - 파트너 부담분 들어간 신규 쿠폰/할인 정책 적용하여 주문 프로세스 로직 수정 개발
            - 신규 쿠폰 & 파트너 정책 테이블 DB 설계 및 어드민 개발         
          * 티몬 주문서 내 정적 데이터(무이자 할부) 캐싱 처리로 응답 속도 개선
          * 위메프 신규 PG사(네이버페이) 연동 
            - 기존 PG사를 통한 네이버페이 결제방식에서 직연동 주문/인증/인증완료/승인/승인취소 API 로직 분석 및 신규 개발
            - 차액정산 SFTP 서버 송수신 개발
            - 구매 금액 네이버페이 포인트 적립 개발
            - 현금성 결제(포인트/머니) 부분사용 시 현금영수증 처리 개발
          * 공공기관 통합검색 사이트 개발
            - Spring Data Elasticsearch를 통한 Elasticsearch 연동 데이터 적재 및 검색 서비스 개발
            - 5개 정부 부처 간 외부 망연계를 통한 통합 검색 API 및 검색화면 구현
          * 윤선생 DBook CMS 컨텐츠 관리 서비스 개발 (리드)
            - 대용량 학습 컨텐츠 AWS Multipart 방식으로 병렬처리 하여 AWS S3에 일괄 업로드 개발
            - 학습 포인트 조회 및 관리 페이지 구현
            - JavaScript를 활용하여 CMS 전체 화면 JSP 구현
          * 학력평가 서비스 개발
            - 평가 로직에 따른 학력평가 시험 진행 및 학습 통계 리포트 API 구현
            - 카카오 알림톡을 이용한 응시 경로/결과 전달 및 신청 링크를 통한 응시 등록 학생 관리 API 구현

      - layout: top-middle
        title: 레거시 시스템 리팩토링
        quote: >
        description: |
          * 티몬 딜 정보 DB 분리에 따른 주문 스냅샷 생성 및 쿼리 변경/개선
            - 일부 쿼리 내에 로직 분리 후 애플리케이션 단으로 이관
            - Slow Query 쿼리 플랜 확인하여 인덱스 조건절 추가
          * 위메프 제휴카드 포인트 적립 Spring Batch 리팩토링
            - 카드사별 데이터 처리에 필요한 공통 로직을 별도로 분리하여 확장 가능한 구조로 개선
            - 전문 미수신시 재시도 & 배치 실패 시 알림 서비스 개발
          * 위메프 승인대사 & 차액정산 배치 통합
            - 일반결제와 간편결제(위메프페이)의 승인대사, 차액정산이 별도 프로젝트로 구현된 부분 하나의 프로젝트로 통합
            - 기존 배치 처리로직 분석 및 불필요한 로직 제거
            - 배치 구조 통일로 유지보수성을 높이고 개별로 관리되던 배치 모니터링 및 관리 일원화

      - layout: top-middle
        title: 기타 운영 업무
        quote: >
        description: | # this will include new lines to allow paragraphs     
          * 신용/체크카드 앱카드 연동, 토스페이, 카카오페이, 페이코, 휴대폰 등 결제 관련 운영개발 업무
          * 티몬/위메프 일마감, 영중소 차액정산, 현금영수증 관련 업무
          * 티몬 금감원 및 카드사 100만건 이상 대용량 데이터 추출 대응

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          * Java
          * Spring Boot, Spring MVC, Spring Batch, Spring Security
          * JPA, Mybatis
          * MySQL, Oracle, Redis, CouchBase, ElasticSearch
          * Gradle, Maven
      - layout: left
        title: DevOps
        description: |
          * Jenkins
          * Nginx, Tomcat
          * Kibana, Datadog
      - layout: left
        title: Frontend
        description: |
          * JavaScript

  - title: Certificate
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SQL 개발자(SQLD)
        caption: 2019.12
        sub_title: 한국데이터산업진흥원
      - layout: left
        title: 정보처리기사
        caption: 2019.11
        sub_title: 한국산업인력공단

# Footer
footer_show_references: false
# references_title: References available upon request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
